# -*- coding: utf-8 -*-
#
# hpc user guide documentation build configuration file, created by
# sphinx-quickstart on Wed Nov 22 14:47:45 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import os
import sys
import subprocess
import shlex
sys.path.insert(0, os.path.abspath('.'))

cmd = 'pip install -r requirements.txt'

placeholder_replacements = {
    "{BRANCH}": "main"
}

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.autosectionlabel',
    'sphinx_tabs.tabs',
    'sphinx-prompt',
    'sphinx_toolbox',
    'sphinx_toolbox.github',
    'sphinx_copybutton',
    'sphinxcontrib.youtube'
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "pydata_sphinx_theme"

html_css_files = []

html_js_files = []

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown',
}

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist"
    # other useful extensions: "deflist", "fieldlist", etc.
]
myst_heading_anchors = 2
todo_include_todos = True

html_theme_options = {
    "external_links": [
        {
            "url": "https://www.aub.edu.lb",
            "name": "AUB",
        },
        {
            "url": "https://servicedesk.aub.edu.lb/TDClient/1398/Portal/Requests/ServiceDet?ID=29749",
            "name": "Research Request form",
        },
        {
            "url": "https://jupyterhub.aub.edu.lb",
            "name": "AUB Jupyterhub",
        },
    ],
    "header_links_before_dropdown": 5,
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/hpcaubuserguide/hpcaub_userguide",
            "icon": "fa-brands fa-github",
        }
    ],
    # alternative way to set twitter and github header icons
    # "github_url": "https://github.com/pydata/pydata-sphinx-theme",
    # "twitter_url": "https://twitter.com/PyData",
    "logo": {
        "text": "AUB HPC wiki",
    },
    "use_edit_page_button": True,
    "show_toc_level": 2,
    # [left, content, right] For testing that the navbar items align properly
    "navbar_align": "left",
    # "show_nav_level": 2,
    #"announcement": "https://raw.githubusercontent.com/pydata/pydata-sphinx-theme/main/docs/_templates/custom-template.html",
    #"show_version_warning_banner": True,
    #"navbar_center": ["version-switcher", "navbar-nav"],
    # "navbar_start": ["navbar-logo"],
    # "navbar_end": ["theme-switcher", "navbar-icon-links"],
    # "navbar_persistent": ["search-button"],
    # "primary_sidebar_end": ["custom-template", "sidebar-ethical-ads"],
    # "article_footer_items": ["test", "test"],
    # "content_footer_items": ["test", "test"],
    "footer_start": ["copyright"],
    "footer_center": ["sphinx-version"],
    "secondary_sidebar_items": {
        "**/*": ["page-toc", "edit-this-page", "sourcelink"],
        "examples/no-sidebar": [],
    },
    #"switcher": {
    #    "json_url": json_url,
    #    "version_match": version_match,
    #},
    # "back_to_top_button": False,
    "search_as_you_type": True,
}

# Configuration required by sphinx_toolbox.github extension
github_username = "hpcaubuserguide"
github_repository = "hpcaub_userguide"

html_context = {
    "default_mode": "light",
    "github_user": "hpcaubuserguide",  # Updated to match your repository
    "github_repo": "hpcaub_userguide",  # Updated to match your repository
    "github_version": "main",
    # the sources live in userdoc/, not docs/ -- with the wrong value here the
    # theme's "Edit on GitHub" button points at a path that does not exist
    "doc_path": "userdoc",
}

project = 'AUB HPC user guide'
copyright = '2025, HPC admin team, IT helpdesk'
author = 'HPC admin team'

todo_include_todos = True