# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "22"
  jobs:
    create_environment:
      - pip install virtualenv
      - virtualenv .venv
      - . .venv/bin/activate
      - pip install build
      - git clone https://github.com/pydata/pydata-sphinx-theme.git
      - cd pydata-sphinx-theme && python3 -m build && cd ..
      - pwd
      - ls -la
      - deactivate
      - pip install -r requirements.txt
      - pip install pydata-sphinx-theme/dist/pydata_sphinx_theme-*.whl

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: userdoc/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
#python:
#  install:
#  - requirements: requirements.txt